import React from 'react';
import Head from 'next/head';

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen w-full bg-white">
    <div className="max-w-4xl mx-auto px-4 py-8">
      <Head>
        <title>Privacy Policy | Yacht International</title>
        <meta name="description" content="Privacy Policy for Yacht International Singapore" />
      </Head>

      <h1 className="text-3xl text-gray-900 font-bold mb-6">Privacy Policy</h1>
      <p className="text-gray-600 mb-8"><em>Last updated: April 09, 2025</em></p>

      <div className="prose max-w-none text-gray-900">
        <section className="mb-8">
          <p className="mb-4">
            This Privacy Policy describes Our policies and procedures on the collection, 
            use and disclosure of Your information when You use the Service and tells You 
            about Your privacy rights and how the law protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By using the 
            Service, You agree to the collection and use of information in accordance with 
            this Privacy Policy. This Privacy Policy has been created with the help of the 
            <a href="https://www.termsfeed.com/privacy-policy-generator/" className="text-blue-600 hover:underline"> Privacy Policy Generator</a>.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Interpretation and Definitions</h2>
          
          <h3 className="text-xl font-medium mb-2">Interpretation</h3>
          <p className="mb-4">
            The words of which the initial letter is capitalized have meanings defined 
            under the following conditions. The following definitions shall have the same 
            meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3 className="text-xl font-medium mb-2">Definitions</h3>
          <p className="mb-4">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Yacht International, 10 Anton Road, International Plaza, Singapore 079903.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: Singapore</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>Website</strong> refers to Yacht International Singapore, accessible from <a href="https://yacht-intl.sg/" className="text-blue-600 hover:underline">https://yacht-intl.sg/</a></li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Collecting and Using Your Personal Data</h2>
          
          <h3 className="text-xl font-medium mb-2">Types of Data Collected</h3>
          
          <h4 className="text-lg font-medium mb-2">Personal Data</h4>
          <p className="mb-4">
            While using Our Service, We may ask You to provide Us with certain personally 
            identifiable information that can be used to contact or identify You. 
            Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li>Usage Data</li>
          </ul>

          <h4 className="text-lg font-medium mb-2">Usage Data</h4>
          <p className="mb-4">
            Usage Data is collected automatically when using the Service.
          </p>
          <p className="mb-4">
            Usage Data may include information such as Your Device's Internet Protocol address 
            (e.g. IP address), browser type, browser version, the pages of our Service that 
            You visit, the time and date of Your visit, the time spent on those pages, unique 
            device identifiers and other diagnostic data.
          </p>
          <p className="mb-4">
            When You access the Service by or through a mobile device, We may collect certain 
            information automatically, including, but not limited to, the type of mobile device 
            You use, Your mobile device unique ID, the IP address of Your mobile device, Your 
            mobile operating system, the type of mobile Internet browser You use, unique device 
            identifiers and other diagnostic data.
          </p>
          <p className="mb-4">
            We may also collect information that Your browser sends whenever You visit our 
            Service or when You access the Service by or through a mobile device.
          </p>

          <h4 className="text-lg font-medium mb-2">Tracking Technologies and Cookies</h4>
          <p className="mb-4">
            We use Cookies and similar tracking technologies to track the activity on Our 
            Service and store certain information. Tracking technologies used are beacons, 
            tags, and scripts to collect and track information and to improve and analyze 
            Our Service. The technologies We use may include:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>
              <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your 
              Device. You can instruct Your browser to refuse all Cookies or to indicate when a 
              Cookie is being sent. However, if You do not accept Cookies, You may not be able 
              to use some parts of our Service.
            </li>
            <li>
              <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain 
              small electronic files known as web beacons that permit the Company, for example, 
              to count users who have visited those pages or opened an email.
            </li>
          </ul>
          <p className="mb-4">
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on 
            Your personal computer or mobile device when You go offline, while Session Cookies 
            are deleted as soon as You close Your web browser. You can learn more about cookies 
            on <a href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies" className="text-blue-600 hover:underline">TermsFeed website</a>.
          </p>
          <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>
              <strong>Necessary / Essential Cookies</strong><br />
              Type: Session Cookies<br />
              Administered by: Us<br />
              Purpose: These Cookies are essential to provide You with services available through 
              the Website and to enable You to use some of its features.
            </li>
            <li>
              <strong>Cookies Policy / Notice Acceptance Cookies</strong><br />
              Type: Persistent Cookies<br />
              Administered by: Us<br />
              Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
            </li>
            <li>
              <strong>Functionality Cookies</strong><br />
              Type: Persistent Cookies<br />
              Administered by: Us<br />
              Purpose: These Cookies allow us to remember choices You make when You use the Website.
            </li>
          </ul>
        </section>

        {/* Continue with other sections following the same pattern */}
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Use of Your Personal Data</h2>
          <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
            <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
            <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract.</li>
            <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
            <li>To provide You with news, special offers and general information about other goods, services and events.</li>
            <li>To manage Your requests: To attend and manage Your requests to Us.</li>
            <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Children's Privacy</h2>
          <p className="mb-4">
            Our Service does not address anyone under the age of 13. We do not knowingly 
            collect personally identifiable information from anyone under the age of 13. 
            If You are a parent or guardian and You are aware that Your child has provided 
            Us with Personal Data, please contact Us.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Links to Other Websites</h2>
          <p className="mb-4">
            Our Service may contain links to other websites that are not operated by Us. 
            If You click on a third party link, You will be directed to that third party's 
            site. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Changes to this Privacy Policy</h2>
          <p className="mb-4">
            We may update Our Privacy Policy from time to time. We will notify You of any 
            changes by posting the new Privacy Policy on this page.
          </p>
          <p className="mb-4">
            You are advised to review this Privacy Policy periodically for any changes. 
            Changes to this Privacy Policy are effective when they are posted on this page.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
          <p className="mb-4">
            If you have any questions about this Privacy Policy, You can contact us:
          </p>
          <ul className="list-disc pl-6">
            <li>By visiting this page on our website: <a href="https://yacht-intl.sg/contact" className="text-blue-600 hover:underline">https://yacht-intl.sg/contact</a></li>
          </ul>
        </section>
      </div>
    </div>
    </div>
  );
};

export default PrivacyPolicy;